name: Publish Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-resume:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Nix devShell (flake)
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Compile with Nix flake
      run: nix develop --command typst compile main.typ resume.pdf

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: resume.pdf
        retention-days: 30

